### ISSUE TITLE
Reported by Jack Alexander

### ISSUE THREAD

**Issue by pconrad** [ucsb-gradescope-tools/ucsb-gradescope-tools.github.io#5]
When trying the scripts locally on CSIL, pip install throws an error... 

Maybe we could do pip install --user everywhere?

Does that work on the Gradescope side?  (It probably does... )

**Comment by caitscarberry** [comment]
Resolved by changes in MAKE-REFERENCE.sh in sample-cpp-diff-autograder and diff-autograder-template. In the future, fixes like this would be easier if MAKE-REFERENCE.sh was in the gs-diff-based-testing repo. This would necessitate adding a separate build.sh to every autograder repo, because Python assignments don't need the `make` and `make clean` steps that C++ assignments need, but it would also ensure that every autograder always gets the most recent version of MAKE-REFERENCE.sh.

@pconrad , what do you think?
